import type { RegistrationDataDto } from "../dto/account";
import type { AutoGeneratedFields } from "./types";
import { AuthProvider, type Account, type PrismaClient } from "@prisma/client";

export default class AccountRepository {
    constructor(private prisma: PrismaClient) {}

    private create = (data: Omit<Account, AutoGeneratedFields>) => {
        return this.prisma.account.create({
            data,
        });
    };

    public createLocal = (
        account: RegistrationDataDto,
        passwordHash: string
    ) => {
        return this.create({
            username: account.username,
            email: account.email,
            firstName: account.firstName,
            lastName: account.lastName,
            provider: AuthProvider.local,
            password: passwordHash,
        });
    };

    public createGoogle = (
        account: Omit<
            RegistrationDataDto,
            "username" | "password" | "confirmPassword"
        >
    ) => {
        return this.create({
            username: null,
            email: account.email,
            firstName: account.firstName,
            lastName: account.lastName,
            provider: AuthProvider.google,
            password: null,
        });
    };

    public async existsByEmailCaseInsensitive(email: string): Promise<boolean> {
        return !!(await this.prisma.account.findFirst({
            where: {
                email: {
                    equals: email,
                    mode: "insensitive",
                },
            },
        }));
    }

    public findByEmailWhereProviderGoogle = (email: string) => {
        return this.prisma.account.findFirst({
            where: {
                email,
                provider: AuthProvider.google,
                password: null,
            },
        });
    };

    public findByEmailCaseInsensitiveWhereProviderLocal = (email: string) => {
        return this.prisma.account.findFirst({
            where: {
                email: {
                    equals: email,
                    mode: "insensitive",
                },
                provider: AuthProvider.local,
                NOT: {
                    password: null,
                },
            },
        });
    };
}
