import type { AuctionCarInformation, City, Prisma } from "@prisma/client";
import type { BASIC_AUCTION_SELECT } from "./select/auction";

export type AutoGeneratedFields = "id" | "createdAt" | "updatedAt";

/**
 * The Type for a "Basic" auction, which is just a auction with a lot less information, made to be shows as a "thumbnail" auction on which the user can then click to go
 * to the full auction. This type looks a bit complicated but it is just prisma magic, if you open @constant BASIC_AUCTION_SELECT you will see
 * exactly what is being returned in the "Basic" auction data
 */
export type BasicAuction = Omit<
    Prisma.AuctionGetPayload<{
        select: typeof BASIC_AUCTION_SELECT;
    }>,
    "bids" | "carInformation"
> & {
    bids: {
        amount: number;
        bidder: {
            username: string;
        };
    }[];
    carInformation: Omit<AuctionCarInformation & { city: City }, "vin">;
};
